# Generated by Django 4.1.6 on 2023-02-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_authorization_url', models.CharField(max_length=100)),
                ('external_access_code', models.CharField(max_length=100)),
                ('external_reference', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('created', 'Created'), ('comleted', 'Completed'), ('failed', 'Failed')], default='created', max_length=100)),
                ('purpose', models.CharField(choices=[('withdrawal', 'Withdrawal'), ('topup', 'Topup')], max_length=100)),
            ],
        ),
    ]
