# Generated by Django 4.1.6 on 2023-02-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_external_access_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('withdrawal', 'Withdrawal'), ('topup', 'Topup'), ('transfer_credit', 'Transfer Credit'), ('transfer_debit', 'Transfer Debit')], max_length=100),
        ),
    ]
