# Generated by Django 4.1.6 on 2023-02-08 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_phone_phone_no_with_ext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='phone_no_with_ext',
            new_name='phone_with_ext',
        ),
    ]
