# Generated by Django 4.1.6 on 2023-02-06 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletentry',
            old_name='ammount',
            new_name='amount',
        ),
    ]
