# Generated by Django 4.1.6 on 2023-02-07 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallets', '0002_rename_ammount_walletentry_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletentry',
            name='entry_type',
            field=models.CharField(choices=[('withdrawal', 'Withdrawal'), ('topup', 'Topup'), ('transfer_credit', 'Transfer Credit'), ('transfer_debit', 'Transfer Debit')], max_length=100),
        ),
        migrations.CreateModel(
            name='WalletTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('comleted', 'Completed'), ('failed', 'Failed')], default='created', max_length=100)),
                ('meta', models.JSONField(default=dict)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transfers', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_transfers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
