# Generated by Django 4.1.6 on 2023-02-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_alter_walletentry_entry_type_wallettransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransfer',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('completed', 'Completed'), ('failed', 'Failed')], default='created', max_length=100),
        ),
    ]
