# Generated by Django 4.1.6 on 2023-02-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_alter_wallettransfer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletentry',
            name='entry_type',
            field=models.CharField(choices=[('withdrawal', 'Withdrawal'), ('reverse_withdrawal', 'Reverse Withdrawal'), ('topup', 'Topup'), ('transfer_credit', 'Transfer Credit'), ('transfer_debit', 'Transfer Debit')], max_length=100),
        ),
    ]
